### ISSUE TITLE
AWS: Newly launched instance in us-west-2 does not successfully run.

### ISSUE THREAD

**Issue by redbeard0x0a** [Graylog2/graylog2-images#39]
Following the instructions for the AWS AMI image in us-west-2 (also of note: the Launch Instance link doesn't work).

I pulled down the image, launched it on a m3.medium instance, ran the reconfigure command and tried to login via http://<vm ip>. I get an error stating that no graylog servers can be reached, unable to login.

It appears that the server that is supposed to be running on port 12900 is not running.

```bash
ubuntu@graylog:/opt/graylog/conf$ sudo netstat -tap | grep LISTEN
tcp        0      0 *:3333                  *:*                     LISTEN      2739/java
tcp        0      0 localhost:2380          *:*                     LISTEN      2747/etcd
tcp        0      0 graylog:9200            *:*                     LISTEN      2739/java
tcp        0      0 *:http                  *:*                     LISTEN      2863/nginx.conf
tcp        0      0 *:46611                 *:*                     LISTEN      2739/java
tcp        0      0 graylog:9300            *:*                     LISTEN      2739/java
tcp        0      0 *:38324                 *:*                     LISTEN      2739/java
tcp        0      0 *:ssh                   *:*                     LISTEN      1123/sshd
tcp        0      0 localhost:afs3-callback *:*                     LISTEN      2747/etcd
tcp6       0      0 [::]:9000               [::]:*                  LISTEN      2802/java
tcp6       0      0 [::]:2379               [::]:*                  LISTEN      2747/etcd
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      1123/sshd
tcp6       0      0 [::]:4001               [::]:*                  LISTEN      2747/etcd
ubuntu@graylog:/opt/graylog/conf$
```

**Comment by mariussturm** [comment]
The link should be fixed now!
I was not able to reproduce your issue. On a m3.medium instance in us-west-2 the reconfigure went through just fine.

```
ubuntu@graylog:~$ sudo netstat -tap | grep LISTEN
tcp        0      0 *:3333                  *:*                     LISTEN      1885/java
tcp        0      0 *:27017                 *:*                     LISTEN      1712/mongod
tcp        0      0 localhost:2380          *:*                     LISTEN      1684/etcd
tcp        0      0 *:42925                 *:*                     LISTEN      1885/java
tcp        0      0 graylog:9200            *:*                     LISTEN      1885/java
tcp        0      0 *:http                  *:*                     LISTEN      1983/nginx.conf
tcp        0      0 graylog:9300            *:*                     LISTEN      1885/java
tcp        0      0 *:ssh                   *:*                     LISTEN      1123/sshd
tcp        0      0 localhost:afs3-callback *:*                     LISTEN      1684/etcd
tcp        0      0 *:52320                 *:*                     LISTEN      1885/java
tcp6       0      0 [::]:12900              [::]:*                  LISTEN      1910/java
tcp6       0      0 [::]:9350               [::]:*                  LISTEN      1910/java
tcp6       0      0 [::]:9000               [::]:*                  LISTEN      1936/java
tcp6       0      0 [::]:2379               [::]:*                  LISTEN      1684/etcd
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      1123/sshd
tcp6       0      0 [::]:4001               [::]:*                  LISTEN      1684/etcd
```
Do you see anything in the Elasticsearch or graylog-server log?

```
sudo tail -f /var/log/graylog/elasticsearch/current
```

```
sudo tail -f /var/log/graylog/server/current
```

In doubt could you try to reproduce this on a new instance. It is possible that your appliance end up on some over comitted host that behaves odd?

**Comment by redbeard0x0a** [comment]
ami-a7426397
t2.medium

Default VPC
- Public IP

Security Group
- SSH 0.0.0.0/0
- HTTP 0.0.0.0/0
- HTTPS 0.0.0.0/0

It is still not working (this is the 3rd new server I have tried). I'm on IRC at the moment, if you want to send me a message so we can figure this out.

```
^Cubuntu@graylog:~$ sudo tail -n 30 /var/log/graylog/server/current
2015-02-24_19:17:27.35331 2015-02-24 19:17:27,353 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.VersionCheckThread] periodical in [0s], polling every [1800s].
2015-02-24_19:17:27.35390 2015-02-24 19:17:27,353 INFO : org.graylog2.periodical.Periodicals - Starting [org.graylog2.periodical.ThrottleStateUpdaterThread] periodical in [1s], polling every [1s].
2015-02-24_19:17:27.84253 2015-02-24 19:17:27,842 INFO : org.elasticsearch.transport - [graylog2-server] bound_address {inet[/0:0:0:0:0:0:0:0:9350]}, publish_address {inet[/172.31.9.182:9350]}
2015-02-24_19:17:27.86822 2015-02-24 19:17:27,868 INFO : org.reflections.Reflections - Reflections took 288 ms to scan 1 urls, producing 2 keys and 2 values
2015-02-24_19:17:27.98855 2015-02-24 19:17:27,988 INFO : org.elasticsearch.discovery - [graylog2-server] graylog2/FmP5zM3UQOOnQ9L0znunfQ
2015-02-24_19:17:27.99497 2015-02-24 19:17:27,994 WARN : org.graylog2.indexer.esplugin.ClusterStateMonitor - No Elasticsearch data nodes in cluster, cluster is completely offline.
2015-02-24_19:17:30.99551 2015-02-24 19:17:30,995 WARN : org.elasticsearch.discovery - [graylog2-server] waited for 3s and no initial state was set by the discovery
2015-02-24_19:17:30.99622 2015-02-24 19:17:30,996 INFO : org.elasticsearch.node - [graylog2-server] started
2015-02-24_19:17:31.21819 2015-02-24 19:17:31,218 INFO : org.elasticsearch.cluster.service - [graylog2-server] detected_master [Mangog][Xyqyp0B3R1W8o-ps9bJgsw][graylog][inet[/172.31.9.182:9300]], added {[Mangog][Xyqyp0B3R1W8o-ps9bJgsw][graylog][inet[/172.31.9.182:9300]],}, reason: zen-disco-receive(from master [[Mangog][Xyqyp0B3R1W8o-ps9bJgsw][graylog][inet[/172.31.9.182:9300]]])
2015-02-24_19:17:35.32291 2015-02-24 19:17:35,322 INFO : org.graylog2.shared.initializers.RestApiService - Adding security context factory: <org.graylog2.security.ShiroSecurityContextFactory@dcccb24>
2015-02-24_19:17:35.33892 2015-02-24 19:17:35,338 INFO : org.graylog2.shared.initializers.RestApiService - Started REST API at <http://0.0.0.0:12900/>
2015-02-24_19:17:35.33926 2015-02-24 19:17:35,339 INFO : org.graylog2.shared.initializers.ServiceManagerListener - Services are healthy
2015-02-24_19:17:35.34075 2015-02-24 19:17:35,340 INFO : org.graylog2.shared.initializers.InputSetupService - Triggering launching persisted inputs, node transitioned from Uninitialized?[LB:DEAD] to Running?[LB:ALIVE]
2015-02-24_19:17:35.34145 2015-02-24 19:17:35,341 INFO : org.graylog2.bootstrap.ServerBootstrap - Services started, startup times in ms: {InputSetupService [RUNNING]=2, OutputSetupService [RUNNING]=4, GroovyShellSetupService [RUNNING]=7, JournalReader [RUNNING]=7, MetricsReporterService [RUNNING]=10, BufferSynchronizerService [RUNNING]=10, KafkaJournal [RUNNING]=12, DashboardRegistryService [RUNNING]=120, PeriodicalsService [RUNNING]=128, IndexerSetupService [RUNNING]=3993, RestApiService [RUNNING]=8099}
2015-02-24_19:17:35.35384 2015-02-24 19:17:35,353 INFO : org.graylog2.bootstrap.ServerBootstrap - Graylog server up and running.
2015-02-24_19:17:37.35593 2015-02-24 19:17:37,355 INFO : org.graylog2.indexer.Deflector - Did not find an deflector alias. Setting one up now.
2015-02-24_19:17:37.35778 2015-02-24 19:17:37,357 INFO : org.graylog2.indexer.Deflector - There is no index target to point to. Creating one now.
2015-02-24_19:17:37.35909 2015-02-24 19:17:37,359 INFO : org.graylog2.indexer.Deflector - Cycling deflector to next index now.
2015-02-24_19:17:37.35920 2015-02-24 19:17:37,359 INFO : org.graylog2.indexer.Deflector - Cycling from <none> to <graylog_0>
2015-02-24_19:17:37.35925 2015-02-24 19:17:37,359 INFO : org.graylog2.indexer.Deflector - Creating index target <graylog_0>...
2015-02-24_19:17:38.00244 2015-02-24 19:17:37,998 INFO : org.graylog2.indexer.Deflector - Done!
2015-02-24_19:17:38.00245 2015-02-24 19:17:37,998 INFO : org.graylog2.indexer.Deflector - Pointing deflector to new target index....
2015-02-24_19:17:38.04338 2015-02-24 19:17:38,043 INFO : org.graylog2.system.jobs.SystemJobManager - Submitted SystemJob <cb826870-bc59-11e4-9356-0a929944dd34> [org.graylog2.indexer.ranges.RebuildIndexRangesJob]
2015-02-24_19:17:38.04345 2015-02-24 19:17:38,043 INFO : org.graylog2.indexer.Deflector - Done!
2015-02-24_19:17:38.04476 2015-02-24 19:17:38,044 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Re-calculating index ranges.
2015-02-24_19:17:38.17483 2015-02-24 19:17:38,174 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Index [graylog_0] is empty, inserting dummy index range.
2015-02-24_19:17:38.17755 2015-02-24 19:17:38,177 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Index [graylog_0] is empty but it is the current deflector target. Inserting dummy index range.
2015-02-24_19:17:38.18032 2015-02-24 19:17:38,180 INFO : org.graylog2.indexer.ranges.RebuildIndexRangesJob - Done calculating index ranges for 1 indices. Took 105ms.
2015-02-24_19:17:38.18157 2015-02-24 19:17:38,181 INFO : org.graylog2.system.jobs.SystemJobManager - SystemJob <cb826870-bc59-11e4-9356-0a929944dd34> [org.graylog2.indexer.ranges.RebuildIndexRangesJob] finished in 136ms.
2015-02-24_19:17:38.53976 2015-02-24 19:17:38,539 INFO : org.hibernate.validator.internal.util.Version - HV000001: Hibernate Validator 5.1.2.Final
ubuntu@graylog:~$ sudo tail -n 30 /var/log/graylog/elasticsearch/current
2015-02-24_19:16:33.40504 	at org.apache.log4j.FileAppender.setFile(FileAppender.java:294)
2015-02-24_19:16:33.40508 	at org.apache.log4j.FileAppender.activateOptions(FileAppender.java:165)
2015-02-24_19:16:33.40512 	at org.apache.log4j.DailyRollingFileAppender.activateOptions(DailyRollingFileAppender.java:223)
2015-02-24_19:16:33.40516 	at org.apache.log4j.config.PropertySetter.activate(PropertySetter.java:307)
2015-02-24_19:16:33.40520 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:172)
2015-02-24_19:16:33.40523 	at org.apache.log4j.config.PropertySetter.setProperties(PropertySetter.java:104)
2015-02-24_19:16:33.40527 	at org.apache.log4j.PropertyConfigurator.parseAppender(PropertyConfigurator.java:842)
2015-02-24_19:16:33.40531 	at org.apache.log4j.PropertyConfigurator.parseCategory(PropertyConfigurator.java:768)
2015-02-24_19:16:33.40535 	at org.apache.log4j.PropertyConfigurator.parseCatsAndRenderers(PropertyConfigurator.java:672)
2015-02-24_19:16:33.40539 	at org.apache.log4j.PropertyConfigurator.doConfigure(PropertyConfigurator.java:516)
2015-02-24_19:16:33.40542 	at org.apache.log4j.PropertyConfigurator.configure(PropertyConfigurator.java:440)
2015-02-24_19:16:33.40546 	at org.elasticsearch.common.logging.log4j.LogConfigurator.configure(LogConfigurator.java:105)
2015-02-24_19:16:33.40550 	at org.elasticsearch.bootstrap.Bootstrap.setupLogging(Bootstrap.java:94)
2015-02-24_19:16:33.40554 	at org.elasticsearch.bootstrap.Bootstrap.main(Bootstrap.java:178)
2015-02-24_19:16:33.40558 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:32)
2015-02-24_19:16:33.40562 log4j:ERROR Either File or DatePattern options are not set for appender [index_search_slow_log_file].
2015-02-24_19:16:40.82182 [2015-02-24 19:16:40,643][INFO ][node                     ] [Mangog] version[1.4.1], pid[1765], build[89d3241/2014-11-26T15:49:29Z]
2015-02-24_19:16:40.82189 [2015-02-24 19:16:40,821][INFO ][node                     ] [Mangog] initializing ...
2015-02-24_19:16:40.83003 [2015-02-24 19:16:40,829][INFO ][plugins                  ] [Mangog] loaded [], sites []
2015-02-24_19:17:13.37074 [2015-02-24 19:17:13,370][INFO ][node                     ] [Mangog] initialized
2015-02-24_19:17:13.37085 [2015-02-24 19:17:13,370][INFO ][node                     ] [Mangog] starting ...
2015-02-24_19:17:13.43177 [2015-02-24 19:17:13,431][INFO ][transport                ] [Mangog] bound_address {inet[/172.31.9.182:9300]}, publish_address {inet[/172.31.9.182:9300]}
2015-02-24_19:17:13.43973 [2015-02-24 19:17:13,439][INFO ][discovery                ] [Mangog] graylog2/Xyqyp0B3R1W8o-ps9bJgsw
2015-02-24_19:17:23.45613 [2015-02-24 19:17:23,455][INFO ][cluster.service          ] [Mangog] new_master [Mangog][Xyqyp0B3R1W8o-ps9bJgsw][graylog][inet[/172.31.9.182:9300]], reason: zen-disco-join (elected_as_master)
2015-02-24_19:17:23.47076 [2015-02-24 19:17:23,470][INFO ][http                     ] [Mangog] bound_address {inet[/172.31.9.182:9200]}, publish_address {inet[/172.31.9.182:9200]}
2015-02-24_19:17:23.47095 [2015-02-24 19:17:23,470][INFO ][node                     ] [Mangog] started
2015-02-24_19:17:23.48596 [2015-02-24 19:17:23,485][INFO ][gateway                  ] [Mangog] recovered [0] indices into cluster_state
2015-02-24_19:17:31.20506 [2015-02-24 19:17:31,204][INFO ][cluster.service          ] [Mangog] added {[graylog2-server][FmP5zM3UQOOnQ9L0znunfQ][graylog][inet[/172.31.9.182:9350]]{client=true, data=false, master=false},}, reason: zen-disco-receive(join from node[[graylog2-server][FmP5zM3UQOOnQ9L0znunfQ][graylog][inet[/172.31.9.182:9350]]{client=true, data=false, master=false}])
2015-02-24_19:17:37.67357 [2015-02-24 19:17:37,673][INFO ][cluster.metadata         ] [Mangog] [graylog_0] creating index, cause [api], shards [4]/[1], mappings []
2015-02-24_19:17:37.98744 [2015-02-24 19:17:37,987][INFO ][cluster.metadata         ] [Mangog] [graylog_0] create_mapping [message]
ubuntu@graylog:~$
```

**Comment by redbeard0x0a** [comment]
The log has a line about successfully starting the RestApiService on port 12900, however I still do not show anything listening on port 12900.

**Comment by mariussturm** [comment]
What's your IRC handle? Would really like to look into this.

**Comment by redbeard0x0a** [comment]
redbeard0x0a

**Comment by mariussturm** [comment]
Will close it for now and see if we can try to reproduce with the server devs

**Comment by redbeard0x0a** [comment]
I haven't seen it crop back up on AWS recently either.
